import { COLOR_EXTENSION_MAP } from "@/constant";

const defaultStyles: { [key: string]: React.CSSProperties } = {
  // Define default styles here based on the color mapping
  pdf: { backgroundColor: COLOR_EXTENSION_MAP.pdf },
  docx: { backgroundColor: COLOR_EXTENSION_MAP.docx },
  doc: { backgroundColor: COLOR_EXTENSION_MAP.doc },
  pptx: { backgroundColor: COLOR_EXTENSION_MAP.pptx },
  ppt: { backgroundColor: COLOR_EXTENSION_MAP.ppt },
  xlsx: { backgroundColor: COLOR_EXTENSION_MAP.xlsx },
  mpeg: { backgroundColor: COLOR_EXTENSION_MAP.mpeg },
  xls: { backgroundColor: COLOR_EXTENSION_MAP.xls },
  jpg: { backgroundColor: COLOR_EXTENSION_MAP.jpg },
  jpeg: { backgroundColor: COLOR_EXTENSION_MAP.jpeg },
  png: { backgroundColor: COLOR_EXTENSION_MAP.png },
  gif: { backgroundColor: COLOR_EXTENSION_MAP.gif },
  txt: { backgroundColor: COLOR_EXTENSION_MAP.txt },
  zip: { backgroundColor: COLOR_EXTENSION_MAP.zip },
  rar: { backgroundColor: COLOR_EXTENSION_MAP.rar },
  mp3: { backgroundColor: COLOR_EXTENSION_MAP.mp3 },
  mp4: { backgroundColor: COLOR_EXTENSION_MAP.mp4 },
  mov: { backgroundColor: COLOR_EXTENSION_MAP.mov },
  avi: { backgroundColor: COLOR_EXTENSION_MAP.avi },
  wav: { backgroundColor: COLOR_EXTENSION_MAP.wav },
  wma: { backgroundColor: COLOR_EXTENSION_MAP.wma },
  m4a: { backgroundColor: COLOR_EXTENSION_MAP.m4a },
  aac: { backgroundColor: COLOR_EXTENSION_MAP.aac },
  svg: { backgroundColor: COLOR_EXTENSION_MAP.svg },
  exe: { backgroundColor: COLOR_EXTENSION_MAP.exe },
  dmg: { backgroundColor: COLOR_EXTENSION_MAP.dmg },
  psd: { backgroundColor: COLOR_EXTENSION_MAP.psd },
  ai: { backgroundColor: COLOR_EXTENSION_MAP.ai },
  ttf: { backgroundColor: COLOR_EXTENSION_MAP.ttf },
  otf: { backgroundColor: COLOR_EXTENSION_MAP.otf },
  json: { backgroundColor: COLOR_EXTENSION_MAP.json },
  csv: { backgroundColor: COLOR_EXTENSION_MAP.csv },
  js: { backgroundColor: COLOR_EXTENSION_MAP.js },
  jsx: { backgroundColor: COLOR_EXTENSION_MAP.jsx },
  ts: { backgroundColor: COLOR_EXTENSION_MAP.ts },
  tsx: { backgroundColor: COLOR_EXTENSION_MAP.tsx },
  py: { backgroundColor: COLOR_EXTENSION_MAP.py },
  java: { backgroundColor: COLOR_EXTENSION_MAP.java },
  rb: { backgroundColor: COLOR_EXTENSION_MAP.rb },
  c: { backgroundColor: COLOR_EXTENSION_MAP.c },
  cpp: { backgroundColor: COLOR_EXTENSION_MAP.cpp },
  cs: { backgroundColor: COLOR_EXTENSION_MAP.cs },
  go: { backgroundColor: COLOR_EXTENSION_MAP.go },
  php: { backgroundColor: COLOR_EXTENSION_MAP.php },
  swift: { backgroundColor: COLOR_EXTENSION_MAP.swift },
  kotlin: { backgroundColor: COLOR_EXTENSION_MAP.kotlin },
  rs: { backgroundColor: COLOR_EXTENSION_MAP.rs },
  sh: { backgroundColor: COLOR_EXTENSION_MAP.sh },
  ps1: { backgroundColor: COLOR_EXTENSION_MAP.ps1 },
  bat: { backgroundColor: COLOR_EXTENSION_MAP.bat },
  cmd: { backgroundColor: COLOR_EXTENSION_MAP.cmd },
  h: { backgroundColor: COLOR_EXTENSION_MAP.h },
  hs: { backgroundColor: COLOR_EXTENSION_MAP.hs },
  lua: { backgroundColor: COLOR_EXTENSION_MAP.lua },
  pl: { backgroundColor: COLOR_EXTENSION_MAP.pl },
  sql: { backgroundColor: COLOR_EXTENSION_MAP.sql },
  vb: { backgroundColor: COLOR_EXTENSION_MAP.vb },
  vue: { backgroundColor: COLOR_EXTENSION_MAP.vue },
  html: { backgroundColor: COLOR_EXTENSION_MAP.html },
  css: { backgroundColor: COLOR_EXTENSION_MAP.css },
  scss: { backgroundColor: COLOR_EXTENSION_MAP.scss },
  sass: { backgroundColor: COLOR_EXTENSION_MAP.sass },
  less: { backgroundColor: COLOR_EXTENSION_MAP.less },
  md: { backgroundColor: COLOR_EXTENSION_MAP.md },
  yml: { backgroundColor: COLOR_EXTENSION_MAP.yml },
};

export default defaultStyles;
